

services:
  # The single PostgreSQL database for the entire application
  postgres_db:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stonks_main_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # The existing user service
  user_service:
    build:
      context: ./services/user_service
    command: npm run start:dev
    ports:
      - "3001:3001"
    volumes:
      - ${PWD}/services/user_service:/usr/src/app
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://user:password@postgres_db:5432/stonks_main_db
    depends_on:
      - postgres_db

  wallet_service:
    build:
      context: ./services/wallet_service
    command: npm run start:dev
    ports:
      - "3002:3002"
    volumes:
      - ${PWD}/services/wallet_service:/usr/src/app
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://user:password@postgres_db:5432/stonks_main_db
    depends_on:
      - postgres_db

volumes:
  postgres_data:
